name: StaticWebSite
summary: This is an App Configuration deployment using Bicep.
description: Deploys an static web site.
templatePath: azuredeploy.json
parameters:
- id: "staticSites_drse_name"
  name: "staticSites_drse_name"
  description: "Name of the App Config"
  type: "string"
  required: true
runner: ARM
