name: SimpleWindowsVM
summary: Deploys a simple Windows VM with public RDP access.
description: Creates a basic Windows virtual machine accessible over a custom RDP port.
runner: ARM
templatePath: azuredeploy.json
parameters:
  - id: vmName
    name: VM Name
    description: Name of the virtual machine
    type: string
    default: simplevm

  - id: adminUsername
    name: Administrator Username
    description: VM admin username
    type: string
    default: azureuser

  - id: adminPassword
    name: Administrator Password
    description: VM admin password
    type: secureString

  - id: rdpPort
    name: RDP Port
    description: Public RDP port to access the VM
    type: integer
    default: 3389

  - id: location
    name: Azure Region
    description: Region to deploy the resources
    type: string
    default: eastus
